name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install tools
        run: |
          python -m pip install --upgrade pip pytest
          pip install -r requirements.txt

      - name: Test with unittest
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GENAI_KEY }}
        run: python3 -m unittest discover -s tests
